### ISSUE TITLE
Sticky element width doesn't update, use max-width instead

### ISSUE THREAD

**Issue by nedkelly** [d-oliveros/ngSticky#138]
When the `sticky` element sticks the current width is applied to the `style` attribute. When resizing the window this size cannot update because it will always be equal to the initial size: `initialCSS.width=width` is the same as `263=263` because you've explicitly declared the width - then retrieved the width.

To fix this use `width: 100%; max-width: XXpx;` instead, this way the element can properly resize.

```css
element.style {
    z-index: 10;
    width: 100%;
    max-width: 233px;
    position: fixed;
    top: 10px;
    margin-top: 0px;
}
```

Cheers.
